"""Add brand fields to teams

Revision ID: 99235959d9ef
Revises: 002_add_branding
Create Date: 2026-02-05 16:22:38.969916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99235959d9ef'
down_revision: Union[str, None] = '002_add_branding'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('brand_domain', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('brand_colors', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('brand_theme', sa.String(length=20), nullable=True))
    op.add_column('teams', sa.Column('brand_font_style', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'brand_font_style')
    op.drop_column('teams', 'brand_theme')
    op.drop_column('teams', 'brand_colors')
    op.drop_column('teams', 'brand_domain')
    # ### end Alembic commands ###
